### ISSUE TITLE
Tab format HTML output, query id clickable error

### ISSUE THREAD

**Issue by aubombarely** [GMOD/mimosa#102]

**Comment by leto** [comment]
Can you describe exactly what the input params are for this? Which blast program, and which tabular format? A link to a cached mimosa report with this problem would be ideal.

**Comment by aubombarely** [comment]
http://mimosa.sgn.cornell.edu:8080/api/sequence/1/gi%7C326731691%7Cgb%7CJI387092.1%7C.fasta

Program: BlastN
Alignment View: Tabular

Onece you have the results, click any of the first column elements
