### ISSUE TITLE
Autocrud is broken

### ISSUE THREAD

**Issue by leto** [GMOD/mimosa#17]
This URL
http://localhost:4000/autocrud/bcs/organismprop

gives:

[error] DBIx::Class::ResultSource::related_source(): Can't find source for Bio::Chado::Schema::Result::Cv::Cvterm at /home/leto/local-lib/lib/perl5/Catalyst/Plugin/AutoCRUD/Model/Metadata/DBIC.pm line 310
[error] Caught exception in App::Mimosa::Controller::AutoCRUD::Root->do_meta "Can't use string ("0") as a HASH ref while "strict refs" in use at /home/leto/local-lib/lib/perl5/Catalyst/Plugin/AutoCRUD/Controller/Root.pm line 136."
[error] Caught exception in App::Mimosa::Controller::AutoCRUD::Root->source "Can't use string ("0") as a HASH ref while "strict refs" in use at /home/leto/local-lib/lib/perl5/Catalyst/Plugin/AutoCRUD/Controller/Root.pm line 84."

**Comment by rbuels** [comment]
use https://github.com/rbuels/Catalyst-Plugin-AutoCRUD/tree/dangling_rels for now, will work on a proper fix for autocrud

**Comment by leto** [comment]
This branch needs to be merged upstream and then this will work :

https://github.com/rbuels/Catalyst-Plugin-AutoCRUD/commit/9cb71b38d1b8f663b75e989557b7f5a48a9c9841

**Comment by rbuels** [comment]
pull req in for autocrud https://github.com/ollyg/Catalyst-Plugin-AutoCRUD/pull/11

**Comment by leto** [comment]
I think this works now.
