### ISSUE TITLE
Need graphical blast summaries

### ISSUE THREAD

**Issue by rbuels** [GMOD/mimosa#31]
Like in the SGN blast tool.

**Comment by leto** [comment]
How do these interact with downloading raw reports?

**Comment by rbuels** [comment]
The raw report does not contain the graphical blast summaries.

Poke at the current SGN BLAST tool to see how it behaves.  Do it like that.

**Comment by leto** [comment]
It relies on a bunch of internal SGN modules to generate graphics. Am I reimplementing all of that, or should we push some of it to CPAN? The code in Bio::GMOD::Blast::Graph is horrific.

**Comment by leto** [comment]
Done.

**Comment by rbuels** [comment]
For the record, Bio::Blast::Graph has been cleaned up a bit and pushed to CPAN by me.

**Comment by leto** [comment]
Still done.
