### ISSUE TITLE
Deployment to existing Chado

### ISSUE THREAD

**Issue by rbuels** [GMOD/mimosa#33]
Need a procedure for installing the mimosa tables into an existing Chado database.

**Comment by rbuels** [comment]
Alice has an existing Chado database.  She wants to use Mimosa with that existing Chado database.  Alice needs a way to add the Mimosa tables to her existing Chado database so that Mimosa can run on it.

**Comment by leto** [comment]
This will require deploying a Chado schema to SQLite to test this feature properly.

**Comment by rbuels** [comment]
Bio::Chado::Schema->connect()->deploy should be sufficient.

**Comment by leto** [comment]
Done
