### ISSUE TITLE
Support selecting multiple sequence sets to blast against

### ISSUE THREAD

**Issue by leto** [GMOD/mimosa#37]

**Comment by rbuels** [comment]
Check box in the first column of the sequence set grid.  User checks the boxes for the sequence sets that they want to align against.  Or something like that.

**Comment by leto** [comment]
User selects multiple mimosa_sequence_sets, controller checks if this combination of seqset's already exists on disk, if not, creates them by concatenating them all and passing that to Bio::GMOD::Database.

**Comment by leto** [comment]
- Modify ExtJS grid to send all selected sequence sets to the form, instead
  of only the first
- When a multi sequence set request comes in, we:
  - Error out if any of the mimosa_sequence_set_id's we were given are invalid
  - sort the list of sequence sets alphabetically by their content SHA1s
  - take the SHA1 of this sorted list of SHA1s, this will be the unique key of this unioned set
  - see if a cached version of this unioned set exists already, i.e. -e t/data/SHA1.seq
  - If it does, use it
  - If not, concatenate all the *.seq files for each sequence set, and save it in the file t/data/SHA1.seq
  - Hand off to Bio::GMOD::Database

**Comment by leto** [comment]
Where is the best place to store the sha1 of the unioned/composite sequence set? The database or the filesystem?

**Comment by leto** [comment]
Consensus is that we will use the sha1 column on the mimosa sequence set table, which was just added in the multiseq branch.

**Comment by leto** [comment]
Modification: we will sort the mimosa_sequence_set_ids in increasing id order instead of by their names. We just need a specific ordering, and this one obviates the need to grab all the names from the database, then sort them.
