### ISSUE TITLE
Job submission integration API

### ISSUE THREAD

**Issue by leto** [GMOD/mimosa#7]

**Comment by rbuels** [comment]
for now, this can just be the input page accepting a POST that can do one or more of: pre-fill the sequence select, select blast dbs and programs, set options for the job

**Comment by leto** [comment]
Since something can just POST to the right place, I am closing this ticket.

**Comment by rbuels** [comment]
This is not implemented yet, though.  How can you justify closing it?

**Comment by rbuels** [comment]
To be clear:  input page (currently this is /) should pre-fill the input form from POSTed data, if present.

**Comment by leto** [comment]
Why not just POST to /submit ? Why are we making / what /submit does?

**Comment by rbuels** [comment]
Example use case:
1. User is on a feature detail page at SGN.  This page contains a sequence.  User wants to see what other stuff that sequence might align to.
2. User clicks a 'BLAST' button on that page that uses either JS or a static form on that feature detail page (with hidden inputs or something) that sends a POST to mimosa at '/' containing just the sequence that the user wants to align.
3. The response from Mimosa to that post is a Mimosa input page in which the input textarea is pre-filled with the POSTed sequence.
4.  User selects BLAST parameters, BLAST database, etc on that input page and submits the Mimosa BLAST job.

**Comment by rbuels** [comment]
The sequence is the most important thing to be populated in this way, but other things should be settable as well.  For example, a nice feature of the population would be if it could pre-select a set of databases using search criteria embedded in the POST.
